# Generated by Django 5.1.2 on 2025-11-10 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=120)),
                ('dni', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=40)),
                ('cobertura', models.CharField(max_length=120)),
                ('medico', models.CharField(max_length=120)),
                ('fecha_cx', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(choices=[('TRAUMATOLOGIA', 'Traumatología'), ('HEMODINAMIA', 'Hemodinamia'), ('CIRUGIA_GENERAL', 'Cirugía General'), ('OTORRINO', 'Otorrino'), ('CIRUGIA_PLASTICA', 'Cirugía Plástica'), ('CARDIOLOGIA', 'Cardiología'), ('UROLOGIA', 'Urología')], max_length=32)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Autorizado', 'Autorizado'), ('Falta materiales', 'Falta materiales'), ('Solicitado', 'Solicitado'), ('Materiales OK', 'Materiales OK'), ('Autorizado material pendiente', 'Autorizado material pendiente'), ('rechazado por cobertura', 'Rechazado por cobertura')], default='Pendiente', max_length=40)),
                ('presupuesto', models.CharField(choices=[('', 'Sin presupuesto'), ('En curso', 'En curso'), ('Aprobado', 'Aprobado')], default='', max_length=24)),
                ('obs_proveedores', models.CharField(blank=True, max_length=255)),
                ('reprogramacion', models.DateField(blank=True, null=True)),
                ('observaciones_reprogramacion', models.CharField(blank=True, max_length=255)),
                ('orden_medica', models.FileField(upload_to='ordenes/')),
                ('dni_file', models.FileField(upload_to='dni/')),
                ('credencial', models.FileField(upload_to='credencial/')),
                ('orden_materiales', models.FileField(blank=True, null=True, upload_to='materiales/')),
                ('subcarpeta_url', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('centro', models.CharField(blank=True, max_length=80)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('rol', models.CharField(choices=[('operador', 'operador'), ('admin', 'admin')], default='operador', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
